### PR TITLE
Update CMake to 3.20.1

### PR DESCRIPTION
**Pull request by EwoutH**
Updates CMake to [3.20.1](https://github.com/Kitware/CMake/releases/tag/v3.20.1) on all images, from 3.19.x.

- Windows: 3.19.6 --> 3.20.1
- Ubuntu: 3.19.1 --> 3.20.1
- macOS: 3.19.2 --> 3.20.1

Also cleaned up some whitespaces (automatically).

### CODE REVIEW

**Comment by EwoutH** [comment]
The Windows download URLs have changed. Do we still want to use the 32-bit variant (`cmake-3.20.1-windows-i386.msi`) or can we switch to the 64-bit (`cmake-3.20.1-windows-x86_64.msi`) installer?

**Comment by EwoutH** [comment]
I think actually the Windows install will fail now @FeodorFitsner, because the current `win32-x86.msi` file doesn't get published anymore. That one got renamed to `windows-i386.msi`. On this I occasion, I was wondering if we could install the 64-bit CMake application, `win64-x64.msi`.

So do you keep installing the 32-bit version of CMake or should we switch to the 64-bit version?

**Comment by FeodorFitsner** [comment]
I think switching to x64 makes sense and "should be" safe?

**Comment by EwoutH** [comment]
I agree, I've implemented those changes in #76.

**Pull request merged**
