### PR TITLE
Vs march 2024

### PR DESCRIPTION
**Pull request by OwenMcDonnell**

### CODE REVIEW

**Comment by vszakats** [comment]
CMake no longer seems to be able to detect OpenSSL 3 after these updates.
This, after pointing `OPENSSL_ROOT_DIR` to either `C:\OpenSSL-v31-*\` 
or `C:\OpenSSL-v32-*\` (from the earlier location `C:\OpenSSL-v30-*\`:
https://ci.appveyor.com/project/curlorg/curl/builds/49535099/job/c8r08t6qcu71lwbl

Any recommendation for solving this?

**Comment by vszakats** [comment]
The layout of the `C:\OpenSSL-v3{1|2}-*\lib\` trees changed. Although I couldn't test it, CMake 3.29.0's `FindOpenSSL` module received an update to adopt those tree changes:

https://gitlab.kitware.com/cmake/cmake/-/commit/1327e0ff75f3997a7af7afdc1809551115211c1c
https://gitlab.kitware.com/cmake/cmake/-/issues/25702

**Comment by OwenMcDonnell** [comment]
Yes, I was just about to link to [this related issue](https://gitlab.kitware.com/cmake/cmake/-/issues/25856) which arises because slproweb OpenSSL installers have changed library locations. It looks likely that a cmake update will address this as I don't see any problem with  the new image's OpenSSL directories. 
I will try to apply a patch before the week is through.

**Comment by vszakats** [comment]
CMake merged a fix, scheduled for v3.29.2:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9402

**Comment by OwenMcDonnell** [comment]
The new images have actually already been deployed with 3.29.1. That fix will have to wait for next image update. If you need any help on scripting an update on your build when they release that fix, let us know.

**Comment by vszakats** [comment]
The latest image with CMake 3.29.1 fixed this for my cases (I bumped to OpenSSL 3.2):
https://ci.appveyor.com/project/libssh2org/libssh2/builds/49579128/job/nmb0a27pmqi3shic#L105
https://ci.appveyor.com/project/curlorg/curl/builds/49579215/job/q0riq2o2k0brg9vc#L47

Thank you @OwenMcDonnell!

**Pull request merged**
